name: Deploy to Aliyun VPS

on:
  push:
    branches:
      - main  # 或者你的主分支名称，如 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.2'  # 使用你指定的 Node.js 版本

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest  # 或指定你使用的特定版本

    - name: Install dependencies
      run: pnpm install

    - name: Build Nextra site
      run: pnpm run build

    - name: Deploy to VPS
      uses: burnett01/rsync-deployments@5.2.3
      with:
        switches: -avzr --delete
        path: out/
        remote_path: ${{ secrets.SERVER_DEPLOY_PATH }}
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_port: ${{ secrets.SERVER_PORT }}
        remote_user: ${{ secrets.SERVER_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}